GA_PostprocessBuild
On windows, UnityEditor.iOS doesn't seem to be there all the time. Added `UNITY_IOS` define for the platform dependent compilation.

In other words, fixing this for windows:
```
Assets/GameAnalytics/Editor/GA_PostprocessBuild.cs(3,19): error CS0234: The type or namespace name `iOS' does not exist in the namespace `UnityEditor'. Are you missing an assembly reference?
```